//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AdoNetModelFirst
{
    using System;
    using System.Collections.Generic;
    
    public partial class LogBooks
    {
        public int Id { get; set; }
        public bool IsDebtor { get; set; }
        public int UsersId { get; set; }
        public int BooksId { get; set; }
    
        public virtual Users Users { get; set; }
        public virtual Books Books { get; set; }
    }
}
